@baseUrl=http://localhost:3000

###
POST {{baseUrl}}/api/mobile/v1/device HTTP/1.1
Content-Type: application/json

{
  "name": "Android Phone",
  "pushToken": "eTxx88nfSla87gZuJcW5mS:APA91bHGxVgSqqRtxwFHD1q9em5Oa6xSP4gO_OZRrqOoP1wjf_7UMfXKsc4uws6rWkqn73jYCc1owyATB1v61mqak4ntpqtmRkNtTey7NQXa0Wz3uQZBWY-Ecbn2rWG2VJRihOzXRId-"
}

###
POST {{baseUrl}}/api/3rdparty/v1/message HTTP/1.1
Content-Type: application/json
Authorization: Basic IUGFXE:v4ejpbeydvjo1h

{
    "message": "Test",
    "ttl": 60,
    "phoneNumbers": [
        "79990001234"
    ]
}

###
GET {{baseUrl}}/api/3rdparty/v1/message/iZo6T9hw7wTuKLQUIP29I HTTP/1.1
Authorization: Basic IUGFXE:v4ejpbeydvjo1h

###
GET {{baseUrl}}/api/mobile/v1/message HTTP/1.1
Authorization: Bearer KuvE4LBXzvy8QO2ZXDDMP

###
PATCH {{baseUrl}}/api/mobile/v1/message HTTP/1.1
Authorization: Bearer KuvE4LBXzvy8QO2ZXDDMP
Content-Type: application/json

[
  {
    "id": "8GHr-tUz6JBRFpTUXDV4w",
    "state": "Pending",
    "recipients": [
      {
        "phoneNumber": "79990001234",
        "state": "Pending"
      }
    ]
  }
]
