@baseUrl={{$dotenv CLOUD__URL}}
@credentials={{$dotenv CLOUD__CREDENTIALS}}
@mobileToken={{$dotenv MOBILE__TOKEN}}
@phone={{$dotenv PHONE}}

###
POST {{baseUrl}}/api/mobile/v1/device HTTP/1.1
Content-Type: application/json

{
  "name": "Android Phone",
  "pushToken": "eTxx88nfSla87gZuJcW5mS:APA91bHGxVgSqqRtxwFHD1q9em5Oa6xSP4gO_OZRrqOoP1wjf_7UMfXKsc4uws6rWkqn73jYCc1owyATB1v61mqak4ntpqtmRkNtTey7NQXa0Wz3uQZBWY-Ecbn2rWG2VJRihOzXRId-"
}

###
POST {{baseUrl}}/api/3rdparty/v1/message HTTP/1.1
Content-Type: application/json
Authorization: Basic {{credentials}}

{
    "message": "{{$localDatetime iso8601}}",
    "ttl": 600,
    "phoneNumbers": [
        "{{phone}}"
    ],
    "simNumber": 1,
    "withDeliveryReport": true
}

###
GET {{baseUrl}}/api/3rdparty/v1/message/IyJP8Iexf55XFhYFHMjcs HTTP/1.1
Authorization: Basic {{credentials}}

###
GET {{baseUrl}}/api/mobile/v1/message HTTP/1.1
Authorization: Bearer {{mobileToken}}

###
PATCH {{baseUrl}}/api/mobile/v1/message HTTP/1.1
Authorization: Bearer {{mobileToken}}
Content-Type: application/json

[
  {
    "id": "-rnEaUz7KObDdokPrzKpM",
    "state": "Delivered",
    "recipients": [
      {
        "phoneNumber": "{{phone}}",
        "state": "Delivered"
      }
    ]
  }
]
